name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up environment
      run: |
        touch .env
        echo "${{ secrets.MONGO_DB_URL }}" > .env

    - name: Restart or Start PM2 App (server.js)
      run: |
        pm2 delete apiServer || true
        pm2 start server.js --name apiServer
        pm2 save
