# This workflow will do a clean installation of node dependencies,
# build the source code, and run tests across different versions of node.
# It also handles starting or restarting your PM2 process (BackendAPI).

name: Node.js CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Set up environment file
      run: |
        touch .env
        echo "${{ secrets.MONGO_DB_URL }}" > .env

    - name: Start or Restart BackendAPI using PM2
      run: |
        # Check if BackendAPI is already running
        if pm2 list | grep -q BackendAPI; then
          echo "Restarting existing BackendAPI process..."
          pm2 restart BackendAPI
        else
          echo "Starting new BackendAPI process..."
          pm2 start server.js --name BackendAPI
        fi

    - name: Save PM2 process list
      run: pm2 save
